name: method-call/main
on:
  workflow_dispatch:
jobs:
  Untitled_1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.6.0
    - uses: "./.github/actions/callecho"
      with:
        arg1: hello
        arg2: world
